### ISSUE TITLE
关于这个项目什么时候更新呢

### ISSUE THREAD

**Issue by turbo0212** [yizhiwang96/deepvecfont-v2#2]
hi，您好，想了解下，这个项目预计什么时候回公开呢

**Comment by qqpann** [comment]
I'm interested too!

**Comment by yizhiwang96** [comment]
Thank @qqpann and @turbo0212 for your interest! Sorry for the delay because I spent a lot of time cleaning the code. Most of the code are now ready and I plan to release the code before the next week.

**Comment by yizhiwang96** [comment]
Code is realsed. If you have any problem using it, please don't hesitate to contact me.  @turbo0212 @qqpann
