### ISSUE TITLE
Plugin for Glyphs app?

### ISSUE THREAD

**Issue by Typofactory** [yizhiwang96/deepvecfont-v2#3]
@yizhiwang96  I know you haven’t released the code yet, but would it be possible to turn this into a plugin for Glyphs app? I was wondering how hard it would be to create an entirely new font editor with AI from the ground up, and decided it probably not worth it, so I went to the next best thing: taking FontForge and then adding some generative AI into it, but then I realized I have no clue how AI works. Then I read your articles and wondered if it was possible to make this a plugin for Glyphs app, as that would require less work and probably make it more accessible to more people.

**Comment by yizhiwang96** [comment]
Hi @Typofactory , Thank for your suggestions. I just find [Glyphs](https://glyphsapp.com/features) is a very interesting app which has a very active community. I will try to learn how to use it and figure out some way that can plug DeepVecFont models into it. Let's keep in touch!
