### ISSUE TITLE
Question abount some characters (e.g., g, p, q ...), The parts below these characters baselines are cut

### ISSUE THREAD

**Issue by XieJinYan1127** [yizhiwang96/deepvecfont-v2#6]
I'm sorry to have raised the same issue with you.
If you could provide me with an answer, I would greatly appreciate it.

Regarding the issue recorded in the following note, it was originally expected to be fixed in deepvecfont-v2, but the actual result was that the problem still occurred in deepvecfont-v2.
https://github.com/yizhiwang96/deepvecfont/issues/33

I used a custom test dataset. This is the generated result.
![image](https://github.com/yizhiwang96/deepvecfont-v2/assets/111431980/c10a0926-3624-4cad-acff-b3fea883720d)

### Question :
May I ask if the reason is that the fix for this issue has not been updated to deepvecfont-v2 yet?

**Comment by yizhiwang96** [comment]
What I meant was: V2 does not need to align the SVGs with the images, so the SVGs won't be missing parts like these images. If your target is only the raster images, you still need to fix the issue by extending the canvas.

**Comment by XieJinYan1127** [comment]
@yizhiwang96  Thank you for your answer.

But not only is the raster image cut off, but the SVG image is also cut off.
![image](https://github.com/yizhiwang96/deepvecfont-v2/assets/111431980/44023527-1b5e-4aef-adb4-f9b8d7e0cf23)

### Question ：
I looked at the preprocessing of the input data and found that in the output of the glyph drawing stage, the glyph has been truncated. My guess is that the data in the input main model itself does not contain the part below the baseline, so this causes these problems. 

１．Is my findings and understanding correct?
２．If I need to resize the canvas so that the glyph is not truncated, it would be helpful if you could tell me in which processes the canvas needs to be resized. （Preprocessing of training sets? Training? Preprocessing of test sets? Test?）

**Comment by yizhiwang96** [comment]
I need to check this issue with the first author Yuqing Wang. In the meantime, could you change the view box in each svg from `viewBox="0 0 24 24` to `viewBox="0 0 24 48"` to see if there is smt underneath?

**Comment by XieJinYan1127** [comment]
@yizhiwang96 
After I changed the viewbox to 24*48, the generated SVG image can now display the full glyph, 
thank you very much for your guidance.

Next, I would like to try a similar approach to modify version 1 so that the test results of version 1 also show the full glyph.
